[metadata]
name = sasci360apiscim
version = 0.0.1
author = Mark Nelson
author_email = support@nelsongrey.com
description = System for Cross-domain Identity Management REST API for SAS Customer Intelligence 360
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mnelson3/sas_ci360_api_scim
project_urls = Bug Tracker = https://github.com/mnelson3/sas_ci360_api_scim/issues
classifiers = Programming Language :: Python :: 3
              License :: Other/Proprietary License
              Operating System :: OS Independent

[install_requires]
package = requests~=2.27.1
          sasci360apicore

[options]
package_dir = = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
